### ISSUE TITLE
response formats

### ISSUE THREAD

**Issue by netzulo** [netzulo/qatestlink#23]
# TODOs

- [x] handle **member** tags in *response xml_str*
  - [x] *1st structure* : ``(member > (name + value > string | int)) * **n**``
  - [x] *2nd structure* : ``name + value > struct > (member > (name + value > string | int )) * **n**``

 ## Issues related 

#21 

### notes

Maybe this doc note helps to fix old tests

``` python
class BaseHandler(object):
    def parse_node_value(self, node_value):
            # TODO: i don't know how to do this yet
            # different response for each request...
            # maybe ResponseMaybe class have no sense 
            # maybe must return dict always ?
```
