### ISSUE TITLE
TODO GLOBAL

### ISSUE THREAD

**Issue by netzulo** [netzulo/qatestlink#7]
# TODOs

+ [ ] create request: ``TPROYECT_CREATE = 'tl.createTestProject'``
+ [ ] create request: ``TPROJECTS = 'tl.getProjects'``
+ [ ] create request: ``TPROJECT_BY_NAME = 'tl.getTestProjectByName'``
+ [ ] create request: ``TPROJECT_TEST_PLANS = 'tl.getProjectTestPlans'``
+ [ ] create request: ``TPROJECT_TSUITES_FIRST_LEVEL = 'tl.getFirstLevelTestSuitesForTestProject'``
+ [ ] create request: ``TPLAN_CREATE = 'tl.createTestPlan'``
+ [ ] create request: ``TPLAN_ADD_TCASE = 'tl.addTestCaseToTestPlan'``
+ [ ] create request: ``TPLAN_BY_NAME = 'tl.getTestPlanByName'``
+ [ ] create request: ``TPLAN_PLATFORMS = 'tl.getTestPlanPlatforms'``
+ [ ] create request: ``TPLAN_TOTALS = 'tl.getTotalsForTestPlan'``
+ [ ] create request: ``TPLAN_BUILDS = 'tl.getBuildsForTestPlan'``
+ [ ] create request: ``TPLAN_BUILD_LATEST = 'tl.getLatestBuildForTestPlan'``
+ [ ] create request: ``TPLAN_EXEC_LATEST = 'tl.getLastExecutionResult'``
+ [ ] create request: ``TPLAN_TSUITES = 'tl.getTestSuitesForTestPlan'``
+ [ ] create request: ``TPLAN_TCASES = 'tl.getTestCasesForTestPlan'``
+ [ ] create request: ``BUILD_CREATE = 'tl.createBuild'``
+ [ ] create request: ``TSUITE_CREATE = 'tl.createTestSuite'``
+ [ ] create request: ``TSUITE_TSUITES = 'tl.getTestSuitesForTestSuite'``
+ [ ] create request: ``TSUITE_BY_ID = 'tl.getTestSuiteByID'``
+ [ ] create request: ``TSUITE_TCASES = 'tl.getTestCasesForTestSuite'``
+ [ ] create request: ``REQ_ASSIGN = 'tl.assignRequirements'``
+ [ ] create request: ``TCASE_REPORT_RESULT = 'tl.reportTCResult'``
+ [ ] create request: ``TCASE_EXEC_RESULT = 'tl.setTestCaseExecutionResult'``
+ [ ] create request: ``TCASE_CREATE = 'tl.createTestCase'``
+ [ ] create request: ``TCASE_ID_BY_NAME = 'tl.getTestCaseIDByName'``
+ [ ] create request: ``TCASE_CUSTOM_FIELD_DESIGN_VALUE = 'tl.getTestCaseCustomFieldDesignValue'``
+ [ ] create request: ``TCASE_ATTACHMENTS = 'tl.getTestCaseAttachments'``
+ [ ] create request: ``TCASE_BY_IDS = 'tl.getTestCase'``
+ [ ] create request: ``TLINK_FULL_PATH = 'tl.getFullPath'``
+ [ ] create request: ``TLINK_EXEC_DELETE = 'tl.deleteExecution'``
+ [ ] create request: ``TLINK_USER_EXIST = 'tl.doesUserExist'``
+ [x] create request: ``TLINK_CHECK_DEV_KEY = 'tl.checkDevKey'``
+ [ ] create request: ``TLINK_ABOUT = 'tl.about'``
+ [ ] create request: ``TLINK_TMODE_TOGGLE = 'tl.setTestMode'``
+ [ ] create request: ``TLINK_PING = 'tl.ping'``
+ [ ] create request: ``TLINK_SAY_HELLO = 'tl.sayHello'``
+ [ ] create request: ``TLINK_REPEAT = 'tl.repeat'``

## Reviewers _only_

You can exec tests with ``python setup.py test``

### Rules before development

* Debug on pytest will be activated on pytest.ini + prints on code **until merge**
* All classes **nomenclature** can be changed **if fix all code behind**
* All functionality can be modified on this PR, add or delete modules, classes, method, ALL
* Ignore setup.py FIXs **while development**
* Ignore utils module **while development**
* Each request must be have 2 tests, **1 for reponse ok, 1 for response ko**

## Documentation:

+ https://github.com/viglesiasce/testlink/blob/master/lib/api/xmlrpc.class.php
  + Search this string ( _CONTROL+F_ ): "tl." # TODOs

**Comment by netzulo** [comment]
Opened issue on testlink while  'tl.getFirstLevelTestSuitesForTestProject' project development

### Issue related 

+ [ ] https://github.com/viglesiasce/testlink/issues/7

**Comment by fmancardi** [comment]
Great if you can test at least the API.
please contact me francisco.mancardi@gmail.com

**Comment by netzulo** [comment]
ty @fmancardi
